### ISSUE TITLE
This is retarded. iostream is retarded. Yours is even worse.

### ISSUE THREAD

**Issue by expnkx** [ShakaUVM/read#1]
```cpp
int a = read<int>(std::cin); WTF????
auto a = read<int>(std::cin); still retarded.
return {};
WTF? why is zero EOF????
```

Stop making things worse than it already is. You cannot fix it in any manner since std::cin just wraps FILE* which is even worse. Your solution is horrible.

https://github.com/expnkx/fast_io/blob/master/examples/0001.helloworld/hw.cc
https://github.com/expnkx/fast_io/blob/master/examples/0002.a%2Bb/dec.cc

**Comment by ShakaUVM** [comment]
Begone, troll

**Comment by expnkx** [comment]
> Begone, troll

You are just objectively wrong. You are the reason why C++ reddit is a place of morons.
