### ISSUE TITLE
Too limited in std versions

### ISSUE THREAD

**Issue by lmachucab** [ShakaUVM/read#2]
This tool is extremely useful, however the code is written to be fairly limiting in what compilers and std versions it can handle. ATM it requires at least C++17 (``#include <optional>``), probably full support for it, as well as ``auto`` return types that IIRC are not correctly supported below VS 2015 that announce C++11 support but don't actually do it fully.

If the idea is to get people to learn C++ it's important to acknowledge that they might be learning it at eg.: college courses using an older but still valid toolchain. Shared Ubuntu toolchain environments, where the "compiler" compiler is still GCC 4.8, quickly come to mind.

I could file a pull request with some changes that raise the reach this library can have, which could contain at least the following changes:

* drop the ``<optional>`` include and the associated ``read_opt`` function for compilers below C++17.
* Offer an alternative function ``T read_or (T alternative, string prompt)`` that ensures a valid value is read, be it from input or from a selected "default" alternative.
* Drop the unnecessary ``auto`` return types in read/read.h lines 141 and 144, which would allow the code to work with VS as far down as VS 2012 and some older versions of GCC.

These three changes would allow the library to be used with any compiler that has support for C++11, or even partial support such as VS 2012-2013 and GCC "c++0x" mode. 

Optionally, further changes to the various variable initialization lines would extend the support as far back as C++03 but i don't plan to examine that as of yet.

**Comment by ShakaUVM** [comment]
It will now work with C++11 and C++14, with less options available, obviously.

**Comment by lmachucab** [comment]
Oohh.... I admittedly expected to work on this during the weekend; i can still give it a pass to see if there's something useful that can be added. Thanks!

**Comment by ShakaUVM** [comment]
Go for it!

Cheers.

________________________________
