### ISSUE TITLE
Implementation bug disregarding input

### ISSUE THREAD

**Issue by Mikadore** [ShakaUVM/read#3]
Hello!
A simple main program like this:
```cpp
#include <iostream> //redundant, but why not
#include "read.h"
int main()
{
    int x = read();
    std::cout << x; 
}
```
Will behave unexpectedly for the following input:
```
111111111111111 11 15
```
It will output `15`.
The same will happen with `read<int>()`

I would expect, that for that input, the integer `11` is returned. The bug here is an odd inconsistency in how standard streams work. Should a stream try to read an integer value not representable by the given type, it will store the maximum possible value into that integer, but the key point here, **it will advance the stream**.

Therefore here in the implementation:
```cpp
				if(!ins) {
					ins.clear(); //Clear error code
					std::string s;
					ins >> s; //Remove the word that caused the error
					continue;
				}
```
The stream will already have advanced, and the next 'word' to be read is `11`, which consequently will get discarded. The function then goes on as expected, and reads in `15`.

I do not as of now have a workable solution to this problem.

**Comment by ShakaUVM** [comment]
This is really odd. I tried seeing if I could solve it via throwing exceptions, but the exceptions don't differ when this bug occurs

**Comment by Mikadore** [comment]
Exceptions might be the path forward generally, staying with the current system though, I will see if implementing something as banal as 
1. Saving the stream position before reading
2. checking whether the stream position has advanced to conditionally "read out" the given value

would solve this

**Comment by Mikadore** [comment]
I think the following approach is the way to go ahead:
https://compiler-explorer.com/z/eM3jPT
It saves the stream position before reading, and then if the stream has advanced, it'll just continue reading in. I will be issuing a PR shortly.
